- name: Install the php_cli packages
  apt:
    name: '{{ item }}'
    state: 'present'
  with_items: '{{ php_cli_packages }}'

- name: Configure php_cli
  ini_file:
    dest: '{{ php_cli_ini_file }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items: '{{ php_options + php_cli_options }}'
