- name: Prevent php_fpm to start on install
  copy:
    content: |-
      #!/bin/sh
      exit 101
    dest: '/usr/sbin/policy-rc.d'
    owner: 'root'
    group: 'root'
    mode: '0755'
  changed_when: False

- name: Install the php_fpm packages
  apt:
    name: '{{ php_fpm_packages_loop }}'
    state: 'present'
  with_items: '{{ php_fpm_packages }}'
  loop_control:
    loop_var: php_fpm_packages_loop

- name: Remove policy-rc.d
  file:
    name: '/usr/sbin/policy-rc.d'
    state: 'absent'
  changed_when: False
