- name: Set php_handlers_reload
  set_fact:
    php_handlers_reload: '{{ php_handlers_reload + ["reload php-fpm"] }}'

- name: Set php_handlers_restart
  set_fact:
    php_handlers_restart: '{{ php_handlers_restart + ["restart php-fpm"] }}'

- name: Prevent php_fpm to start on install
  copy:
    content: |-
      #!/bin/sh
      exit 101
    dest: '/usr/sbin/policy-rc.d'
    owner: 'root'
    group: 'root'
    mode: '0755'
  changed_when: False

- name: Install the php_fpm packages
  apt:
    name: '{{ item }}'
    state: 'present'
    update_cache: 'yes'
  with_items: '{{ php_fpm_packages }}'

- name: Remove policy-rc.d
  file:
    name: '/usr/sbin/policy-rc.d'
    state: 'absent'
  changed_when: False

- name: Configure php_fpm
  ini_file:
    dest: '{{ php_fpm_ini_file }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items: '{{ php_options + php_fpm_options }}'
  notify: restart php-fpm

- name: Configure www pool
  ini_file:
    dest: '{{ php_fpm_pools_dir }}/www.conf'
    section: 'www'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items: '{{ php_fpm_default_pool_options + php_fpm_pool_options }}'
  notify: restart php-fpm

- name: Ensure /run/php dir exists
  file:
    path: '/run/php'
    state: 'directory'
    owner: '{{ php_fpm_user }}'
    group: '{{ php_fpm_group }}'
    mode: '0755'

- include: 'fpm_{{ php_fpm_init_system }}.yml'
