- name: Set php_handlers_reload
  set_fact:
    php_handlers_reload: '{{ php_handlers_reload + ["reload php-fpm"] }}'

- name: Set php_handlers_restart
  set_fact:
    php_handlers_restart: '{{ php_handlers_restart + ["restart php-fpm"] }}'

- include: 'fpm-{{ php_fpm_loop }}.yml'
  with_items:
    - 'install'
    - 'configure'
    - '{{ php_fpm_init_system }}'
  loop_control:
    loop_var: php_fpm_loop
