---
# tasks file for php

- block:
    - include: 'requirements.yml'

    - include: 'cli.yml'
      when: php_cli
      tags:
        - php-cli

    - include: 'fpm.yml'
      when: php_fpm
      tags:
        - php-fpm

    - include: 'mod.yml'
      when: php_mod
      tags:
        - php-mod

    - include: 'modules.yml'
  tags:
    - php

