---
# tasks file for php

- name: Add ondrej apt key
  apt_key:
    keyserver: 'keyserver.ubuntu.com'
    id: '14AA40EC0831756756D7F66C4F4EA0AAE5267A6C'
    state: 'present'
  tags:
    - php

- name: Install ondrej repo for latest PHP packages
  apt_repository:
    repo: '{{ item }}'
  with_items:
    - 'deb http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_lsb.codename }} main'
    - 'deb-src http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_lsb.codename }} main'
  tags:
    - php

- include: 'cli.yml'
  when: php_cli
  tags:
    - php
    - php-cli

- include: 'fpm.yml'
  when: php_fpm
  tags:
    - php
    - php-fpm

- include: 'mod.yml'
  when: php_mod
  tags:
    - php
    - php-mod

- name: Install modules
  apt:
    name: 'php{{ php_version }}-{{ item }}'
    state: 'present'
    update_cache: 'yes'
  with_items: '{{ php_modules }}'
  tags:
    - php
