- name: Set php_handlers_reload
  set_fact:
    php_handlers_reload: '{{ php_handlers_reload + ["reload apache"] }}'

- name: Set php_handlers_restart
  set_fact:
    php_handlers_restart: '{{ php_handlers_restart + ["restart apache"] }}'

- name: Install the php_mod packages
  apt:
    name: '{{ item }}'
    state: 'present'
  with_items: '{{ php_mod_packages }}'

- name: Configure php_mod
  ini_file:
    dest: '{{ php_mod_ini_file }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items: '{{ php_options + php_mod_options }}'
  notify: restart apache
