- name: Include the php_mod variables
  include_vars: 'mod.yml'

- name: Install the php_mod packages
  apt:
    name: '{{ item }}'
    state: 'present'
    update_cache: 'yes'
  with_items: '{{ php_mod_packages }}'

- name: Configure php_mod
  ini_file:
    dest: '{{ php_mod_ini_file }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items: '{{ php_options + php_mod_options }}'
  notify: restart apache
