---
# handlers file for php

- name: restart php
  shell: >
    /bin/true
  notify: '{{ php_handlers_restart }}'

- name: reload php
  shell: >
    /bin/true
  notify: '{{ php_handlers_reload }}'

- name: restart php-fpm
  service:
    name: '{{ php_fpm_service }}'
    state: 'restarted'

- name: reload php-fpm
  service:
    name: '{{ php_fpm_service }}'
    state: 'reloaded'
